name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Set BASE_URL for Local Testing
        run: echo "BASE_URL=http://localhost:8083" >> $GITHUB_ENV

      - name: Build Project (Run Locally)
        run: npm start &  # Start the app in the background

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Set up Playwright for UI Tests
        run: npx playwright install

      - name: Run UI Tests (Local)
        run: npm run test:ui

      - name: Display SoftUni Username
        run: echo "yamacheva"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Application to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_DEPLOY_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true

      - name: Set BASE_URL for Deployed Testing
        run: echo "BASE_URL=https://yamacheva-prepexam4.onrender.com" >> $GITHUB_ENV

      - name: Smoke UI Tests (Deployed App)
        run: npm run test:ui
