name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm start &

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Set up Playwright for UI Tests
        run: npx playwright install 

      - name: Run UI Tests
        run: npm run test:ui

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build-and-test   
#     steps:
#         - name: Checkout Code
#           uses: actions/checkout@v4
  
#         - name: Deploy Application to Render
#           uses: JorgeLNJunior/render-deploy@v1.4.4
#           with:
#             service_id: ${{ secrets.MY_RENDER_DEPLOY_ID }}
#             api_key: ${{ secrets.MY_RENDER_API_KEY }}
#             wait_deploy: true
    
    softUni:
      runs-on: ubuntu-latest
      
      steps:
      - name: Display SoftUni Username
        run: |
          echo "SoftUni Username: yamacheva"